name: build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PUBLISH_SUFFIX: snapshots
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK (Java 17)
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: gradlew Permission Grant
        run: chmod +x gradlew

      - name: Build w/ Gradle
        run: ./gradlew buildOrPublish

      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/